src/models/Collection.py
from main import db
from models.Playlist import Playlist

collection_playlists = db.Table("collection_playlists",
    db.Column('collection_id', db.Integer, db.ForeignKey('collections.collection_id')),
    db.Column('playlist_id', db.Integer, db.ForeignKey('playlists.playlist_id'))
)

class Collection(db.Model):
    __tablename__ = "collections"

    collection_id = db.Column(db.Integer, primary_key = True)
    name = db.Column(db.String(), nullable = False)
    owner_id = db.Column(db.Integer,db.ForeignKey('users.id'), nullable=False)
    description = db.Column(db.String())
    collaborative = db.Column(db.Boolean(), nullable=False)
    public = db.Column(db.Boolean(), nullable=False)
    collection_playlists = db.relationship('Playlist', secondary=collection_playlists, backref=db.backref('collection_playlists', lazy='dynamic'))

src/models/Playlist.py
from main import db
from models.Track import Track

playlist_tracks = db.Table("playlist_tracks",
    db.Column('playlist_id', db.Integer, db.ForeignKey('playlists.playlist_id')),
    db.Column('track_id', db.Integer, db.ForeignKey('tracks.track_id'))
)

class Playlist(db.Model):
    __tablename__ = "playlists"

    playlist_id = db.Column(db.Integer, primary_key = True)
    name = db.Column(db.String(), nullable = False)
    owner_id = db.Column(db.Integer,db.ForeignKey('users.id'),nullable=False)
    description = db.Column(db.String())
    collaborative = db.Column(db.Boolean(), nullable=False)
    public = db.Column(db.Boolean(), nullable=False)
    playlist_tracks = db.relationship('Track', secondary=playlist_tracks, backref=db.backref('playlist_tracks', lazy='dynamic'))

src/models/Profile.py
from main import db                                                                  # This is the db instance created by SQLAlchemy

class Profile(db.Model):                                                             # Creating a Profile class inheriting from db.Model
    __tablename__ = "profiles"                                                       # Explicitally providing the name of the table

    id = db.Column(db.Integer, primary_key=True)                                     # Creates a column called id and sets it al the primary key
    username = db.Column(db.String(20), nullable=False, unique=True)                   # Profilename, string, must be present, must be unique
    firstname = db.Column(db.String(), nullable=False)                               # Firstname, string, must be present
    lastname = db.Column(db.String(), nullable=False)                                # Lastname, string, must be present
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)       # user_id is an integer and the Foreign key comes from the users table id. It is required

    def __repr__(self):                                                              
        return f"<Profile {self.username}>"                                          # When the Profile is printed it now shows the username instead of the id

src/controllers/collections_controller.py
from main import db
from flask import Blueprint, request, jsonify, abort, render_template
from models.Collection import Collection
from models.User import User
from schemas.CollectionSchema import collection_schema, collections_schema
from services.auth_service import verify_user
from sqlalchemy.orm import joinedload
from flask_jwt_extended import jwt_required, get_jwt_identity

collections = Blueprint("collections", __name__, url_prefix="/collections")

@collections.route("/", methods=["GET"])
def collection_index():
    collections = Collection.query.options(joinedload("owner")).all()
    return jsonify(collections_schema.dump(collections))

@collections.route("/web/", methods=["GET"])
def display_collection():
    collections = Collection.query.options(joinedload("owner")).all()
    return render_template("collections.html", collections=collections)

@collections.route("/", methods=["POST"])
@jwt_required
@verify_user
def collection_create(user=None):
    #Create a new collection
    collection_fields = collection_schema.load(request.json)
    
    new_collection = Collection()
    new_collection.name = collection_fields["name"]
    new_collection.description = collection_fields["description"]
    new_collection.collaborative = collection_fields["collaborative"]
    new_collection.public = collection_fields["public"]
    
    user.collections.append(new_collection)

    db.session.commit()

    return jsonify(collection_schema.dump(new_collection))

@collections.route("/<int:id>", methods=["GET"])
def collection_show(id):
    #Return a single playlist
    collection = Collection.query.get(id)
    return jsonify(collection_schema.dump(collection))

@collections.route("/<int:id>", methods=["PUT", "PATCH"])
@jwt_required
@verify_user
def collection_update(id, user=None):
    #Update a book
    collection_fields = collection_schema.load(request.json)
    
    collections = Collection.query.filter_by(collection_id=id, owner_id=user.id)
    if collections.count() != 1:
        return abort(401, description="Unauthorised to update this book")
    
    collections.update(collection_fields)
    db.session.commit()

    return jsonify(collection_schema.dump(collections[0]))

@collections.route("/<int:id>", methods=["DELETE"])
@jwt_required
@verify_user
def collection_delete(id, user=None):
    collection = Collection.query.filter_by(collection_id=id, owner_id=user.id).first()
    if not collection:
        return abort(400)

    db.session.delete(collection)
    db.session.commit()

    return jsonify(collection_schema.dump(collection))

@collections.route("/count", methods=["GET"])
@jwt_required
@verify_user
def collection_count(user=None):
    if user.is_admin == False:
        return abort(401, description="Unauthorised to this feature")

    query = db.session.query(Collection)

    count = query.count()
    return jsonify(count)

src/controllers/playlists_controller.py
from main import db
from flask import Blueprint, request, jsonify, abort, render_template
from models.Playlist import Playlist
from models.User import User
from schemas.PlaylistSchema import playlist_schema, playlists_schema
from services.auth_service import verify_user
from sqlalchemy.sql import func, label, expression
from sqlalchemy.orm import joinedload
from flask_jwt_extended import jwt_required, get_jwt_identity

playlists = Blueprint("playlists", __name__, url_prefix="/playlists")

@playlists.route("/", methods=["GET"])
def playlist_index():
    playlists = Playlist.query.options(joinedload("owner")).all()
    return jsonify(playlists_schema.dump(playlists))

@playlists.route("/web/", methods=["GET"])
def display_playlist():
    playlists = Playlist.query.options(joinedload("owner")).all()
    return render_template("playlists.html", playlists=playlists)

@playlists.route("/", methods=["POST"])
@jwt_required
@verify_user
def playlist_create(user=None):
    #Create a new playlist
    playlist_fields = playlist_schema.load(request.json)
    
    new_playlist = Playlist()
    new_playlist.name = playlist_fields["name"]
    new_playlist.description = playlist_fields["description"]
    new_playlist.collaborative = playlist_fields["collaborative"]
    new_playlist.public = playlist_fields["public"]
    
    user.playlists.append(new_playlist)

    db.session.commit()

    return jsonify(playlist_schema.dump(new_playlist))

@playlists.route("/<int:id>", methods=["GET"])
def playlist_show(id):
    #Return a single playlist
    playlist = Playlist.query.get(id)
    return jsonify(playlist_schema.dump(playlist))

@playlists.route("/<int:id>", methods=["PUT", "PATCH"])
@jwt_required
@verify_user
def playlist_update(id, user=None):
    #Update a playlist
    playlist_fields = playlist_schema.load(request.json)
    
    playlists = Playlist.query.filter_by(playlist_id=id, owner_id=user.id)
    if playlists.count() != 1:
        return abort(401, description="Unauthorised to update this playlist")
    
    playlists.update(playlist_fields)
    db.session.commit()

    return jsonify(playlist_schema.dump(playlists[0]))

@playlists.route("/<int:id>", methods=["DELETE"])
@jwt_required
@verify_user
def playlist_delete(id, user=None):
    playlist = Playlist.query.filter_by(playlist_id=id, owner_id=user.id).first()
    if not playlist:
        return abort(400)

    db.session.delete(playlist)
    db.session.commit()

    return jsonify(playlist_schema.dump(playlist))

@playlists.route("/count", methods=["GET"])
@jwt_required
@verify_user
def playlist_count(user=None):
    if user.is_admin == False:
        return abort(401, description="Unauthorised to this feature")

    query = db.session.query(Playlist)

    count = query.count()
    return jsonify(count)

src/controllers/profiles_controller.py
import os
import json
from models.Profile import Profile                                     # Importing the Profile Model
from models.User import User, load_user                                           # Importing the User Model
from schemas.ProfileSchema import profile_schema, profiles_schema      # Importing the Profile Schema
from main import db                                                    # This is the db instance created by SQLAlchemy
from main import bcrypt                                                # Import the hasing package from main
from services.auth_service import verify_user 
from sqlalchemy.orm import joinedload                                  # 
from flask_jwt_extended import jwt_required, get_jwt_identity          # Packages for authorization via JWTs
from flask import Blueprint, request, jsonify, abort, render_template, redirect, url_for                   # Import flask and various sub packages
from flask_login import login_required, current_user

from schemas.UserSchema import users_schema
from schemas.ProfileSchema import profiles_schema
from schemas.TrackSchema import tracks_schema
from schemas.PlaylistSchema import playlists_schema
from schemas.CollectionSchema import collections_schema
from schemas.ArtistSchema import artists_schema
from schemas.AlbumSchema import albums_schema
from schemas.AlbumTypeSchema import album_type_schema

profiles = Blueprint("profiles", __name__, url_prefix="/profile")      # Creating the profile blueprint 

tables = ["users", "profiles", "tracks", "playlists", "collections", "artists", "albums", "album_types"]
schemas = [users_schema, profiles_schema, tracks_schema, playlists_schema, collections_schema, artists_schema, albums_schema, album_type_schema ]

@profiles.route("/", methods=["GET"])                                  # Route for the profile index
def profile_index():                                                   # This function will run when the route is matched
    profiles = Profile.query.options(joinedload("user")).all()         # Retrieving all profiles from the db
    return jsonify(profiles_schema.dump(profiles))                     # Returning all the profiles in json

@profiles.route("/", methods=["POST"])                                 # Route for the profile create
@jwt_required                                                          # JWT token is required for this route
@verify_user                                                           # Auth service to make sure the correct user owns this profile
def profile_create(user):                                              # This function will run when the route is matched

    if user.profile != []:                                             # If the user already has a profile
        return abort(400, description="User already has profile")      # Return the error "Email already in use"

    profile_fields = profile_schema.load(request.json)                 # Retrieving the fields from the request
    profile = Profile.query.filter_by(username=profile_fields["username"]).first() # Query the user table with the email and return the first user

    if profile:                                                        # If a user is returned 
        return abort(400, description="username already in use")       # Return the error "Email already in use"

    new_profile = Profile()                                            # Create a new profile object from the Profile model 
    new_profile.username = profile_fields["username"]                  # Add username to the new_profile 
    new_profile.firstname = profile_fields["firstname"]                # Add username to the new_profile 
    new_profile.lastname = profile_fields["lastname"]                  # Add username to the new_profile 
    new_profile.user_id = user.id                                      # Add username to the new_profile 
    
    user.profile.append(new_profile)                                   # Add profile to the user
    db.session.commit()                                                # Commit the DB session
      
    return jsonify(profile_schema.dump(new_profile))                   # Return the newly created profile

@profiles.route("/<int:id>", methods=["GET"])                          # Route for the profile create
def profile_show(id):                                                  # Auth service to make sure the correct user owns this profile
    profile = Profile.query.get(id)                                    # Query the user table with the id then return that user
    return jsonify(profile_schema.dump(profile))                       # Returb the profile in JSON

@profiles.route("/web/", methods=["GET"])                          
def display_profile():                                                  
    user = load_user(current_user.get_id())
    profile = Profile.query.filter_by(
        user_id=user.id).order_by(Profile.id)

    return render_template("profiles.html", profile=profile)
    

@profiles.route("/<int:id>", methods=["PUT", "PATCH"])                 # Route for the profile create
@jwt_required                                                          # JWT token is required for this route
@verify_user                                                           # Auth service to make sure the correct user owns this profile
def profile_update(user, id):                             
    
    profile_fields = profile_schema.load(request.json)                 # Retrieving the fields from the request
    profile = Profile.query.filter_by(id=id, user_id=user.id)          # Query the user table with the id and the user id then return the first user
    if not profile:                                                    # If there is no profile found
        return abort(401, description="Unauthorized to update this profile")  # Return this error

    print(profile.__dict__)
    profile.update(profile_fields)                                     # Update the fields with the data from the request
    db.session.commit()                                                # Commit the session to the db
    return jsonify(profile_schema.dump(profile[0]))                    # Return the recently committed profile


@profiles.route("/<int:id>", methods=["DELETE"])                       # Route for the profile create
@jwt_required        
@verify_user                                                           # Auth service to make sure the correct user owns this profile
def profile_delete(user, id):
    profile = Profile.query.filter_by(id=id, user_id=user.id).first()  # Query the user table with the id and the user id then return the first user
    # print(profile[0].__dict__)
    # return("bills")
    if not profile:                                                    # If there is any number other than 1
        return abort(400, description="Unauthorized to update this profile") # Return this error
    
    db.session.delete(profile)
    db.session.commit()                                                # Commit the session to the db
    return jsonify(profile_schema.dump(profile))                       # Return the deleted profile


@profiles.route("dump/all/<int:id>", methods=["GET"])
@jwt_required
@verify_user
def profile_dump(user, id):
    profile = db.session.query(Profile).filter(Profile.user.is_admin == True).filter_by(id=id, user_id=user.id).first()
  
    if not profile:
        return abort(400, description="Unauthorised to complete this action")
    i=0
    try:
        os.remove("backup/backup.json")
        print("file successfully deleted")
    except:
        print("file does not exist")
    for table in tables:        
        query = db.engine.execute(f'SELECT * FROM {table}')
        data = ((schemas[i]).dump(query))

        print(data)

        data = json.dumps(data)
        i+=1
    
        file = open("backup/backup.json", "a")
        file.write(data)
        file.close()
    return "Data backed up"

src/templates/collections.html
{% extends "layout.html" %}

{% block content %}
    {% for collection in collections %}
    <div class="col px-md-5"><div class="p-3 border bg-light">
                <div class="card" >
                    <div class="card-body">
                        <h5 class="card-title">Collection : {{collection.name}}</h5>
                        <h6 class="card-subtitle mb-2 text-muted">Created by : {{collection.owner.profile[0].username}}</h6>
                        <a href="#" class="card-link">Details</a>
                    </div>
                </div>
            </div>
    </div>
    {% endfor %}
{% endblock %}

src/templates/layout.html
<!doctype html>
<html>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <head>
        <title> SPOTIFY EXTENSION </title>
    </head>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">SPOTIFY</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('collections.display_collection') }}">Collection <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('playlists.display_playlist') }}">Playlist <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Track <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Album <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Artist</a>
            </li>
          </ul>
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
          <div class="navbar-nav">
            {% if current_user.is_authenticated %}
              <a class="nav-item nav-link" href="{{ url_for('profiles.display_profile') }}">Profiles</a>
              <a class="nav-item nav-link" href="{{ url_for('users.user_logout') }}">Logout</a>
            {% else %}
              <a class="nav-item nav-link" href="{{ url_for('users.login_page') }}">Login</a>
              <a class="nav-item nav-link" href="{{ url_for('users.register_page') }}">Register</a>
            {% endif %}
          </div>
        </div>
      </nav>


    <body>
        <div class="container">
        {% with messages = get_flashed_messages(with_categories=true) %}
          {% if messages %}
            {% for category, message in messages %}
              <div class="alert alert-{{ category }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
        {% endwith %}
        {% block content %}

        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        {% endblock %}
        </div>
    </body>
</html>

src/templates/login.html
{% extends "layout.html" %}

{% block content %}
    <div>
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Login</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid")}}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors%}
                                <span>{{ error }}</span>
                            {% endfor%}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid")}}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors%}
                                <span>{{ error }}</span>
                            {% endfor%}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
            <small class="text-muted ml-2">
                <a href="#">Forgot Password?</a>
            </small>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('users.register_page')}}">Sign up Now</a>
        </small>
    </div>
{% endblock %}

src/templates/playlists.html
{% extends "layout.html" %}

{% block content %}
    {% for playlist in playlists %}
    <div class="col px-md-5"><div class="p-3 border bg-light">
                <div class="card" >
                    <div class="card-body">
                        <h5 class="card-title">Playlist : {{playlist.name}}</h5>
                        <h6 class="card-subtitle mb-2 text-muted">Created by : {{playlist.owner.profile[0].username}}</h6>
                        <a href="#" class="card-link">Details</a>
                    </div>
                </div>
            </div>
    </div>
    {% endfor %}
{% endblock %}

src/templates/profiles.html
{% extends "layout.html" %}

{% block content %}
    <div>
      <h1>Your Profile</h1>    
      <div>
        <p class="text-secondary">Email : {{ current_user.email }}</p>
      </div>
      <div>
        <p class="text-secondary">Username : {{ profile.username }}</p>
        <p class="text-secondary">First Name : {{ profile.firstname }}</p>
        <p class="text-secondary">Last Name : {{ profile.lastname }}</p>
      </div>
    </div>
    
    
{% endblock %}

src/templates/register.html
{% extends "layout.html" %}

{% block content %}
    <div>
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Register Today</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid")}}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors%}
                                <span>{{ error }}</span>
                            {% endfor%}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid")}}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors%}
                                <span>{{ error }}</span>
                            {% endfor%}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid")}}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors%}
                                <span>{{ error }}</span>
                            {% endfor%}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Already Have An Account? <a class="ml-2" href="{{ url_for('users.login_page')}}">Sign In</a>
        </small>
    </div>
{% endblock %}